#!/bin/bash
#SBATCH --job-name=franMEP_DQN_0.05
#format could be dd-hh:mm:ss, hh:mm:ss, mm:ss, or mm
#SBATCH --time=7-0:0:0
# #SBATCH --qos=long
#SBATCH --nodes=1
#SBATCH --mem=20000
#SBATCH -p mc 
#SBATCH --mail-type=END,FAIL 
#SBATCH --mail-user=xzhang11@stanford.edu

cd /home/users/xzhang11/axiom/axiom/scripts/works/frankMEP

# Start Run 

sleep 1
#python generate_network.py
python test_DQN_search.py

wait
